# Generated by Django 4.2.11 on 2024-04-25 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inf236backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_termino', models.DateTimeField()),
                ('descripcion', models.TextField()),
                ('estado', models.BooleanField()),
                ('motor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inf236backend.motor')),
            ],
        ),
        migrations.CreateModel(
            name='Mecanico',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('turno', models.CharField(max_length=100)),
                ('disponibilidad', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Progreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_progreso', models.DateTimeField()),
                ('descripcion', models.TextField()),
                ('incidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inf236backend.incidencia')),
                ('mecanico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inf236backend.mecanico')),
            ],
        ),
    ]
