# Generated by Django 4.2.11 on 2024-05-14 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inf236backend', '0002_incidencia_mecanico_progreso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('patente', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=256)),
                ('modelo', models.CharField(max_length=256)),
                ('kilometraje', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('sistema', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialMotorCamion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_retiro', models.DateTimeField()),
                ('fecha_asignacion', models.DateTimeField()),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inf236backend.camion')),
                ('motor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inf236backend.motor')),
            ],
        ),
    ]
