# Generated by Django 4.2.11 on 2024-06-06 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inf236backend', '0004_remove_mecanico_disponibilidad_remove_mecanico_turno_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mecanico',
            old_name='contrasena',
            new_name='contraseña',
        ),
    ]
