# Generated by Django 4.2.11 on 2024-06-06 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inf236backend', '0005_rename_contrasena_mecanico_contraseña'),
    ]

    operations = [
        migrations.CreateModel(
            name='JefeMotores',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('contraseña', models.CharField(default='default_password', max_length=20)),
            ],
        ),
    ]
