# Generated by Django 4.2.11 on 2024-06-29 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inf236backend', '0007_alter_progreso_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MecanicosAsignados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inf236backend.incidencia')),
                ('mecanico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inf236backend.mecanico')),
            ],
        ),
    ]
