# Generated by Django 4.2.11 on 2024-06-29 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inf236backend', '0008_mecanicosasignados'),
    ]

    operations = [
        migrations.AddField(
            model_name='motor',
            name='estado',
            field=models.CharField(default='desconocido', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motor',
            name='marca',
            field=models.CharField(default='desconocido', max_length=256),
            preserve_default=False,
        ),
    ]
