# Generated by Django 4.2.11 on 2024-06-29 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inf236backend', '0009_motor_estado_motor_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='motor',
            name='camion',
            field=models.CharField(default='nose', max_length=256),
            preserve_default=False,
        ),
    ]
