# Generated by Django 4.2.11 on 2024-07-01 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inf236backend', '0010_motor_camion'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='tipo_incidencia',
            field=models.CharField(default='desconocido', max_length=256),
            preserve_default=False,
        ),
    ]
