# Generated by Django 4.2.11 on 2024-07-01 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inf236backend', '0011_incidencia_tipo_incidencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialmotorcamion',
            name='camion',
        ),
        migrations.RemoveField(
            model_name='historialmotorcamion',
            name='motor',
        ),
        migrations.DeleteModel(
            name='Sistema',
        ),
        migrations.RemoveField(
            model_name='jefemotores',
            name='email',
        ),
        migrations.RemoveField(
            model_name='mecanico',
            name='email',
        ),
        migrations.DeleteModel(
            name='Camion',
        ),
        migrations.DeleteModel(
            name='HistorialMotorCamion',
        ),
    ]
