# Generated by Django 4.2.11 on 2024-09-10 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inf236backend', '0015_remove_motor_camion'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialAntecedentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField()),
                ('nombre', models.CharField(max_length=256)),
                ('descripcion', models.TextField()),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inf236backend.camion')),
            ],
        ),
    ]
